version: '3.8'
services:
  mysql:
    container_name: mysql
    env_file:
      - .env
    image: mysql    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: base_datos_prueba
    ports:
      - 3306:3306    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    image: app:dev
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000