version: '3.8'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  app:
    image: application
    container_name: application
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    